from turtle import *
def A() :
    left(70)
    forward(50)
    a = position()
    forward(50)
    right(140)
    forward(100)
    penup()
    setx(a[0])
    sety(a[1])
    pendown()
    left(70)
    forward(35)
    right(90)
    penup()
    forward(45)
    left(90)
    forward(25)
    pendown()
    penup()
    forward(10)
    pendown()


def B() :
    left(90)
    penup()
    forward(10)
    pendown()
    forward(90)
    right(90)
    forward(10)
    for i in range(70):
        right(2.5)
        forward(1)
    left(180)
    for i in range(75):
        right(2.5)
        forward(1)
    forward(10)

    penup()
    left(180)
    forward (30)
    forward(10)
    pendown()

def C():
    penup()
    forward(70)
    left(180)
    pendown()
    forward(10)
    for i in range(180):
        right(1)
        forward(1)

    penup()
    right(90)
    forward(100)
    left(90)
    forward(10)
    pendown()

def D():
    left(90)
    forward(100)
    right(90)
    for i in range(165):
        right(1.1)
        forward(1)
    penup()
    forward(10)
    pendown()

def E():
    left(90)
    forward(100)
    right(90)
    forward(40)
    left(180)
    forward(40)
    left(90)
    forward(50)
    left(90)
    forward(40)
    left(180)
    forward(40)
    left(90)
    forward(50)
    left(90)
    forward(40)
    penup()
    forward(10)
    pendown()

def F():
    left(90)
    forward(100)
    right(90)
    forward(40)
    left(180)
    forward(40)
    left(90)
    forward(50)
    left(90)
    forward(40)
    left(180)
    forward(40)
    left(90)
    forward(50)
    penup()
    left (90)
    forward(40)
    penup()
    forward(10)
    pendown()


def G() :
    penup()
    forward(60)
    left(90)
    forward(70)
    pendown()
    forward(15)
    for i in range(120):
        left(1.5)
        forward(1)
    forward(60)
    for i in range(120):
        left(1.5)
        forward(1)
    forward(10)
    left(90)
    forward(20)
    left(180)
    forward(40)
    penup()
    forward(10)
    pendown()

def H():
    left(90)
    forward(100)
    left(180)
    forward(50)
    left(90)
    forward(50)
    left(90)
    forward(50)
    left(180)
    forward(100)
    penup()
    forward(10)
    pendown()
    penup()
    forward(10)
    pendown()

def I():
    forward(50)
    penup()
    left(180)
    forward(25)
    right(90)
    pendown()
    forward(100)
    left(90)
    forward(25)
    penup()
    left(180)
    forward(15)
    pendown()
    forward(25)
    penup()
    right(90)
    forward(100)
    left(90)
    penup()
    forward(10)
    pendown()
    penup()
    forward(10)
    pendown()

def J() :
    penup()
    forward(40)
    left(90)
    forward(30)
    pendown()
    forward(70)
    left(90)
    forward(20)
    left(180)
    forward(40)
    left(180)
    forward(20)
    left(90)
    forward(70)
    for i in range(50):
        right(3)
        forward(1)
    penup()
    forward(10)
    pendown()

def K() :
    left(90)
    forward(100)
    left(180)
    forward(50)
    left(145)
    forward(65)
    left(180)
    forward(65)
    left(80)
    forward(65)
    penup()
    forward(10)
    pendown()

def L() :
    left(90)
    forward(100)
    left(180)
    forward(100)
    left(90)
    forward(50)
    penup()
    forward(10)
    pendown()

def M() :
    left(90)
    forward(100)
    right(135)
    forward(50)
    left(90)
    forward(50)
    right(135)
    forward(100)
    left(90)
    penup()
    forward(10)
    pendown()
    done()
def N():
    pendown()
    left(90)
    forward(100)
    right(145)
    forward(120)
    left(145)
    forward(90)
    penup()
    left(180)
    forward(100)
    left(90)
    forward(10)
    pendown()
    penup()
    forward(10)
    pendown()

def O() :
    left(90)
    penup()
    forward(30)
    pendown()
    forward(40)
    for i in range (90):
        right(2)
        forward(1)
    forward(40)
    for i in range(90) :
        right(2)
        forward(1)
    penup()
    forward(10)
    pendown()
def P() :
    left(90)
    forward(100)
    right(90)
    for i in range(90):
        right(2)
        forward(1)
    penup()
    forward(10)
    pendown()

def Q() :
    left(90)
    penup()
    forward(30)
    pendown()
    forward(40)
    for i in range (90):
        right(2)
        forward(1)
    forward(40)
    for i in range(90) :
        right(2)
        forward(1)
    right(90)
    penup()
    forward(30)
    right(45)
    pendown()
    forward(50)
    penup()
    forward(10)
    pendown()

def R():
    left(90)
    forward(100)
    right(90)
    for i in range(90):
        right(2)
        forward(1)
    left(90)
    left(45)
    forward(60)
    penup()
    forward(10)
    pendown()

def S() :
    forward(20)
    for loop in range(60):
        forward(1.25)
        left(3)
    for loop in range(70):
        forward(1.25)
        right(3)
    penup()
    forward(10)
    pendown()
def T() :
    penup()
    forward(50)
    pendown()
    left(90)
    forward(100)
    left(90)
    forward(50)
    left(180)
    forward(100)
    penup()
    right(90)
    forward(100)
    left(90)
    pendown()
    penup()
    forward(10)
    pendown()

def () :
    penup()
    left(90)
    forward(100)
    left(180)
    pendown()
    forward(60)
    for i in range (90):
        left(2)
        forward(1)
    forward(60)
    penup()
    forward(10)
    pendown()

def ():
    left(90)
    penup()
    forward(100)
    right(155)
    pendown()
    forward(100)
    left(130)
    forward(100)
    right(155)
    penup()
    forward(100)
    left(90)
    pendown()
    penup()
    forward(10)
    pendown()

def W() :
    penup()
    left(90)
    forward(100)
    right(165)
    pendown()
    forward(100)
    left(145)
    forward(100)
    right(140)
    forward(100)
    left(145)
    forward(100)
    penup()
    forward(10)
    pendown()

def X(): #revoir
    left(45)
    forward(100)
    left(180)
    forward(50)
    left(90)
    forward(50)
    left(180)
    forward(100)
    penup()
    forward(10)
    pendown()
def Y() :
    left(60)
    forward(50)
    a = position()
    forward(50)
    penup()
    setx(a[0])
    sety(a[1])
    pendown()
    left(70)
    forward(50)
    penup()
    forward(10)
    pendown()

def Z() :
    forward(50)
    left(130)
    forward(90)
    right(130)
    forward(50)
    penup()
    forward(10)
    pendown()
